// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.message.hello;

public final class HelloOuterClass {
  private HelloOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_message_hello_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_message_hello_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_message_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_message_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_message_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_message_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\036com.zpb.protobuf.message." +
      "hello\"?\n\005Hello\022\n\n\002id\030\001 \001(\003\022\013\n\003age\030\002 \001(\005\022" +
      "\014\n\004name\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\"~\n\014HelloR" +
      "equest\022\017\n\002id\030\005 \001(\003H\000\210\001\001\022\020\n\003age\030\006 \001(\005H\001\210\001" +
      "\001\022\021\n\004name\030\007 \001(\tH\002\210\001\001\022\024\n\007address\030\010 \001(\tH\003\210" +
      "\001\001B\005\n\003_idB\006\n\004_ageB\007\n\005_nameB\n\n\010_address\" " +
      "\n\rHelloResponse\022\017\n\007message\030\t \001(\t2\276\003\n\014Hel" +
      "loService\022h\n\tsayHello1\022,.com.zpb.protobu" +
      "f.message.hello.HelloRequest\032-.com.zpb.p" +
      "rotobuf.message.hello.HelloResponse\022j\n\ts" +
      "ayHello2\022,.com.zpb.protobuf.message.hell" +
      "o.HelloRequest\032-.com.zpb.protobuf.messag" +
      "e.hello.HelloResponse0\001\022j\n\tsayHello3\022,.c" +
      "om.zpb.protobuf.message.hello.HelloReque" +
      "st\032-.com.zpb.protobuf.message.hello.Hell" +
      "oResponse(\001\022l\n\tsayHello4\022,.com.zpb.proto" +
      "buf.message.hello.HelloRequest\032-.com.zpb" +
      ".protobuf.message.hello.HelloResponse(\0010" +
      "\001B\005P\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zpb_protobuf_message_hello_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_protobuf_message_hello_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_message_hello_Hello_descriptor,
        new java.lang.String[] { "Id", "Age", "Name", "Address", });
    internal_static_com_zpb_protobuf_message_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zpb_protobuf_message_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_message_hello_HelloRequest_descriptor,
        new java.lang.String[] { "Id", "Age", "Name", "Address", "Id", "Age", "Name", "Address", });
    internal_static_com_zpb_protobuf_message_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zpb_protobuf_message_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_message_hello_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
