// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.message.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.message.hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 5;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 5;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional int32 age = 6;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>optional int32 age = 6;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>optional string name = 7;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 7;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 7;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string address = 8;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 8;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 8;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
