// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.message.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.message.hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 9;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 9;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
